### ISSUE TITLE
Images no longer saved in default path

### ISSUE THREAD

**Issue by szpak** [Tommy-Geenexus/exif-eraser#24]
Recently, I've noticed that exif-eraser no longer saves images in default path:

1. Share with ExifEraser.
2. Default save path.
3. Share with something else (or just cancel).

Expected (old behavior):
Image is save in default path.

Actual (current) behavior:
Image can be shared, but I see nothing new in the default save path.

Nevertheless, it seems to remove exif data, as when I share stripped image with Total Commander to save it on disk, it is fine.

In general, if you found a way to keep the stripped images temporarily in memory while sharing, it's nice. However, if it started to be saved in internal storage or any other "special location", it might be harder to periodically remove old processed images.

4.2.1 on Android 11. The last saved image is dated to 28 II 2021, so it started to occur in 4.2.1 or maybe 4.2.0.

**Comment by Tommy-Geenexus** [comment]
Thanks for bringing this to my attention. The image handling has been changed in the most recent version, shared images will currently be stored in the apps private folder regardless of what destination will be selected (side effect of working around an issue in earlier versions preventing proper instrumentation tests).

This will be fixed in the next version.

**Comment by Tommy-Geenexus** [comment]
This has been fixed.

**Comment by Tommy-Geenexus** [comment]
> Thanks. Where is that "apps private folder"? I would like to manually remove old photos, once the next release it available.

The next release will include a settings option to delete accumulated images stored in the app-private directory.
If you want to delete them immediately, you can clear the app's data in the android settings.

**Comment by szpak** [comment]
No immediate action needed. I will patiently wait for the next version.
