### ISSUE TITLE
Unable to share picture with exif-eraser anymore

### ISSUE THREAD

**Issue by szpak** [Tommy-Geenexus/exif-eraser#25]
After upgrade to 4.2.3, I'm not able to share any picture with exif-erase.

Steps to reproduce:
1. Gallery -> Picture (jpg) -> Share -> ExifEraser

Excepted result:
`Choose save path` "dialog at the bottom

Actual result:
"Choose your preferred image source" page with no way to do anything with shared image.

**Comment by szpak** [comment]
Update. I've checked also with some other apps (Total Command and stocked Camera) and with them it worked as expected. The problem seems to be limited only to [Simple Gallery Pro](https://github.com/SimpleMobileTools/Simple-Gallery/), which accidentally as also upgraded 2 days ago to 6.19.6.

If you don't see any recent change that could make that effect, I will ask the Simple Gallery author about his changes.

Pixel 3a, Android 11.

**Comment by szpak** [comment]
Btw2, looking breifly at the recent changes in Simple Gallery Pro, I have found that [change](https://github.com/SimpleMobileTools/Simple-Commons/commit/c9c5682bc1a43eb495c598cc3014ea19a0f53946) in its common library. Do you think it might somehow affect ExifEraser?

**Comment by Tommy-Geenexus** [comment]
@szpak 
Nothing has changed in ExifEraser.
You have located the commit which is causing the issue.

A single image shared with ExifEraser has an improper MIME type (text/uri-list) instead of image/jpeg,
and as such is flagged as unsupported.
If you share multiple images everything works fine.

**Comment by Tommy-Geenexus** [comment]
> Btw, do you have any hints what should be ask for? Simple Gallery still is able to share files with Messages or Total Commander, so it might be somehow limited to (specific for) ExifEraser...

You may ask the author of said app to create a ClipData with a proper Uri MIME type (i.e. not using ClipData.newRawUri() but ClipData.newUri() instead)
