### ISSUE TITLE
Fails when multiple photos

### ISSUE THREAD

**Issue by Thewisem** [Tommy-Geenexus/exif-eraser#26]
When I pick a file directory, most of the photos fail. All the time

**Comment by Tommy-Geenexus** [comment]
@Thewisem 
Could you please share more details?
Did you verify that the images contain metadata, and if so which?

It is very unlikely that this is a bug as opposed to expected behaviour.

**Comment by Thewisem** [comment]
Hmmm ok

**Comment by Thewisem** [comment]
Btw I will obscure my pictures if that's alright with you

**Comment by Thewisem** [comment]
![Screenshot_20210510-155416](https://user-images.githubusercontent.com/74511929/117662234-04516f80-b1a8-11eb-927d-a2932361ed1b.jpg)
![obscura1620651325237](https://user-images.githubusercontent.com/74511929/117662382-29de7900-b1a8-11eb-844a-d8d9fed565ad.jpg)

**Comment by Thewisem** [comment]
![Screenshot_20210510-155416](https://user-images.githubusercontent.com/74511929/117662618-6ca05100-b1a8-11eb-9c3e-9d7e8fc9411b.jpg)

![obscura1620651393886](https://user-images.githubusercontent.com/74511929/117662576-601bf880-b1a8-11eb-9255-8ef3ca3c8eba.jpg)

**Comment by Tommy-Geenexus** [comment]
@Thewisem 
Did you check if those images actually contain metadata (i.e. strip one image at a time)?
What's the outcome with similar apps?

**Comment by Tommy-Geenexus** [comment]
Closing for now, if there is any evidence that this is not expected behaviour this can be reopened.
