### ISSUE TITLE
latest release adds non-free dependency

### ISSUE THREAD

**Issue by IzzySoft** [Tommy-Geenexus/exif-eraser#30]
Going by the release notes, that's most likely the "in-app updates via Google Play". Maybe that could be singled out by using build flavors, so an entirely free APK could be provided at `releases/`?

Background: your app is [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.none.tom.exiferaser) (be welcome to use [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there), which is used by folks who rather avoid Google Play and prefer entirely free apps. I'll now have to add the `NonFreeDep` anti-feature to point out the app uses non-free dependencies, which might scare away some users. That could be avoided :wink:

Apart from that: is it really needed to have in-app updates? Isn't it the task of the app-store app to take care for updates?

**Comment by Tommy-Geenexus** [comment]
I have created a FOSS branch with the offending commits excluded.
Also the 4.3.0 release has been updated with a FOSS version.

>Apart from that: is it really needed to have in-app updates? Isn't it the task of the app-store app to take care for updates?
>
The benefit of having in-app updates is that the developer has full control over the time constraints (i.e. forcing updates onto devices, e.g. critical updates  ).

**Comment by IzzySoft** [comment]
Wow, that was fast – gracias mille! I've adjusted my updater to only pick the `*foss*.apk` from now on, and replaced the 4.3.0 APK with the FOSS variant (thus avoiding the `NonFreeDep`, which will disappear in less than 3h with the next sync).

Not sure if I wanted to have updates *forced* upon me. "Strongly suggested" is fine, though :smile:

Thanks again! :green_heart:
