### ISSUE TITLE
Add an option of 'Always select Default directory'

### ISSUE THREAD

**Issue by hellyeahmfs** [Tommy-Geenexus/exif-eraser#31]
Add an option for user to always select default saving directory and not choosing a custom one everytime.

**Comment by Tommy-Geenexus** [comment]
If you specify a default save path in settings, you can simply select that instead of choosing a custom directory.

**Comment by hellyeahmfs** [comment]
Yeah i know that. I just don't want to select that default path each time so it can work like Scrambled Exif.

**Comment by Tommy-Geenexus** [comment]
Scrambled Exif is a fundamentally different app. I don't think the time saved is worth the cost of development at this point.

**Comment by hellyeahmfs** [comment]
Ok but you can atleast reopen this issue so that you can address it later if you want.
