### ISSUE TITLE
Possible signing certificate checksum mismatch

### ISSUE THREAD

**Issue by ZBE69** [Tommy-Geenexus/exif-eraser#32]
Hello,

It is my understanding that the signing certificate checksum provided in the release section is simply the SHA-256 digest, in which case it doesn't match the actual checksum:
```
> apksigner verify --min-sdk-version 30 --verbose --print-certs gh-exif-eraser.apk
Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
Signer #1 certificate DN: CN=Tom Geiselmann, L=Staig, ST=Baden-Wuerttemberg, C=49
Signer #1 certificate SHA-256 digest: d910867ce2cf3dcd37db51853ebef8633fd83a142b2642274ed068152ff12201
Signer #1 certificate SHA-1 digest: 6b61c0efea270bc27992d3979a9c213d2ab93d83
Signer #1 certificate MD5 digest: d28da5bf0bdd3e4a0b4b4a29c43abc81
```

Specifically:
```D9:10:86:7C:E2:CF:3D:CD:37:DB:51:85:3E:BE:F8:63:3F:D8:3A:14:2B:26:42:27:4E:D0:68:15:2F:F1:22:01```

Compared to:
```75:33:E0:83:FF:A3:35:2A:34:5B:BE:B6:26:06:6F:51:C3:1C:29:26:35:91:AD:4B:4E:83:5F:AD:DD:F6:17:DE```

**Comment by Tommy-Geenexus** [comment]
You are correct, i've double checked with keytool and the certificate fingerprint should be the one you've listed.
Somehow this got messed up during the transition, i'll update the releases with the proper fingerprint.
