### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by yephny** [Tommy-Geenexus/exif-eraser#40]
It'd be great if the app was in the offficial F-Droid repository. Would you mind adding the app to it?

**Comment by Tommy-Geenexus** [comment]
There are currently no plans to distribute ExifEraser via F-Droid.

**Comment by yephny** [comment]
Thanks for your answer. It'd be nice to have the apk from a trustworthy source, but that won't be happening any time soon, I guess.

**Comment by BSGalvan** [comment]
@yephny if you trust it, there is a (regularly updated) [build of ExifEraser](https://apt.izzysoft.de/fdroid/index/apk/com.none.tom.exiferaser) in the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid/index/info).

**Comment by yephny** [comment]
@BSGalvan That's exactly the same as the one on Github.

**Comment by BSGalvan** [comment]
Yes, you are correct!
I suggested that just as an alternative to the Google Play Store :D
