### ISSUE TITLE
Differences between foss apk and. apk

### ISSUE THREAD

**Issue by blogdemoi** [Tommy-Geenexus/exif-eraser#43]
Hi,
What are the differences between the foss apk and the regular apk in the release section?
Thank you.

**Comment by Tommy-Geenexus** [comment]
FOSS and regular are the exact same except for the inclusion of a google play sdk which enables in-app updates in the regular version (which are not active currently, so there is no functional difference at all as of now).

**Comment by blogdemoi** [comment]
OK, thank you.
