### ISSUE TITLE
SVG for the ExifEraser logo

### ISSUE THREAD

**Issue by matchboxbananasynergy** [Tommy-Geenexus/exif-eraser#44]
Hello there! I am currently working on a PR that will add ExifEraser to https://privacyguides.org. (PR can be found here: https://github.com/privacyguides/privacyguides.org/pull/1471)

To be able to complete the PR, I need an SVG of the logo. I looked in the repo and wasn't able to find something. Would you happen to have it handy?

Apologies if it already exists somewhere, or if this is not the appropriate place to ask for this.

Thank you!

**Comment by Tommy-Geenexus** [comment]
![logo](https://user-images.githubusercontent.com/6190487/174957342-1ebbc644-5bcc-4e7a-b1ab-85d7ff525de1.svg)

Here you go.
