### ISSUE TITLE
Option to overwrite original file

### ISSUE THREAD

**Issue by theshininginception** [Tommy-Geenexus/exif-eraser#45]
It would be great

Like -overwrite_original option from exiftool

**Comment by Tommy-Geenexus** [comment]
> It would be great
> 
> Like -overwrite_original option from exiftool

Implementing this is not as straight forward as one would hope, due to the file handling on Android. I will leave this open for consideration, but for the time being this is considered low-priority.

**Comment by meanssaddles** [comment]
if overwrite isn't possible is it doable to have an option to auto-deleted the original after task done? or should i open a new issue to suggest that?

**Comment by Tommy-Geenexus** [comment]
> if overwrite isn't possible is it doable to have an option to auto-deleted the original after task done?
> 
Auto-delete and overwrite are the same thing implementation-wise.
Both require write permission access to an image.

**Comment by Tommy-Geenexus** [comment]
This is implemented (as auto-delete), with the downside being that it does not work with file provider images (shared and photo picker), which means another configuration has to be added which enables the old file selection behaviour.
