### ISSUE TITLE
What does the button on the bottom right do?

### ISSUE THREAD

**Issue by matchboxbananasynergy** [Tommy-Geenexus/exif-eraser#46]
Within the ExifEraser app, there's a square button on the bottom right that has 6 little circles, and two checkmarks once clicked on.

It's unclear to me what this button/option does. Is there any documentation that explains it?

If not, I would really appreciate it if you could shed some light on that!

Thanks!

**Comment by Tommy-Geenexus** [comment]
Clicking it allows you to reorder the image source cards above the button (via drag and drop), clicking it again saves the configuration to local storage.

**Comment by matchboxbananasynergy** [comment]
> Clicking it allows you to reorder the image source cards above the button (via drag and drop), clicking it again persists the new image source order to local storage.

Thank you so much for the reply. I would've never figured that out for myself. I'm not exactly sure how it could be made more clear, but I'm sure I'm not the only one who didn't quite understand what the button did at first.
