### ISSUE TITLE
Share image to app directly from gallery and reopen share menu after exif erased

### ISSUE THREAD

**Issue by hkaancaliskan** [Tommy-Geenexus/exif-eraser#48]
First of all, I would like to thank you for this great app. It's fast and doing it's job :)

I wish we were able to share images from gallery to exif eraser and then exif eraser does its job and opens share menu without saving to directory or anything.

Exact steps:
1- Share an image in gallery to exif eraser
2- Exif eraser clears exif in the background and reopens share menu to share "exif removed" copy
3- Then user can share that image to where ever they want like facebook or instagram etc

[Scrambled Exif ](https://play.google.com/store/apps/details?id=com.jarsilio.android.scrambledeggsif) has this feature but this app much more faster that's why I requested.
<img src="https://user-images.githubusercontent.com/17825767/179301311-bfe47bfb-0f9e-4d6a-86b6-264757d448aa.png" width="300">

**Comment by hkaancaliskan** [comment]
@Tommy-Geenexus I thought you're asking for clear description with "question" label. I tried to make it clear. Hope i did it.

**Comment by Tommy-Geenexus** [comment]
> @Tommy-Geenexus I thought you're asking for clear description with "question" label. I tried to make it clear. Hope i did it.

Thanks, i added the label but haven't had time to respond yet.
I did think of adding something alike initially, but decided to ditch it.

I'm torn on whether this would be worth the effort to implement.

>
> Also i set default directory but app asks everytime, imo that shouldn't be asked if default set.

This could be something worth investigating.

**Comment by Tommy-Geenexus** [comment]
This is now implemented.
Allowing the skipping of the save path selection should be good enough, you may now configure the app to open the share menu without a single tap.
