### ISSUE TITLE
Keys for Play Store release and Github Releases APK

### ISSUE THREAD

**Issue by matchboxbananasynergy** [Tommy-Geenexus/exif-eraser#49]
Hey there! I'm noticing that when I update the app via the Github Releases APK, it also shows up as updated on the Play Store (or Aurora Store, more specifically). Does the Play Store version and the version on Github use the same signing keys (which I assume would be your keys instead of Play app signing)?

In that case, what about the two versions in every release? there seems to be the release and foss-release APKs. Are those signed with the same keys? Are there any functional differences between the two?

**Comment by Tommy-Geenexus** [comment]
> Hey there! I'm noticing that when I update the app via the Github Releases APK, it also shows up as updated on the Play Store (or Aurora Store, more specifically). Does the Play Store version and the version on Github use the same signing keys (which I assume would be your keys instead of Play app signing)?
> 
> In that case, what about the two versions in every release? there seems to be the release and foss-release APKs. Are those signed with the same keys? Are there any functional differences between the two?

All versions have the same applicationId, which is the UID that the Play Store uses to determine uniqueness.

Functionally, there are no differences between FOSS/regular versions. The regular version includes an In-App-Update feature, which is currently unused.
