### ISSUE TITLE
directory mode doesn't rename fully on android

### ISSUE THREAD

**Issue by meanssaddles** [Tommy-Geenexus/exif-eraser#52]
when i try single or multiple image, the file name get replaced by a running number (Screenshot_2022-09-06-13-13-56-915_com.discord become 26892 for example) but when i use directory mode, the part of a filename still retained its original name e.g. Screenshot_2022-09-06-13-13-56-915_com.discord become Screenshot_2022-09-06-13-13-56-915_com (which i want them to be removed)

is it possible to make the app fully rename in directory mode as well?

**Comment by Tommy-Geenexus** [comment]
> when i try single or multiple image, the file name get replaced by a running number (Screenshot_2022-09-06-13-13-56-915_com.discord become 26892 for example) 

This app does not rename images at all, it only add a suffix (if specified in settings).
> 
> is it possible to make the app fully rename in directory mode as well?

Renaming is not a feature planned to be integrated into this application.

If you think there is a bug which causes a file to be renamed in an unexpected manner, feel free to post instructions here which would help me reproduce this potential bug.

**Comment by meanssaddles** [comment]
huh so this is a bug? here is the clip https://media.discordapp.net/attachments/813042041739149363/1016759235444486164/Screenrecorder-2022-09-07-00-16-35-463.mp4

**Comment by Tommy-Geenexus** [comment]
> huh so this is a bug? here is the clip https://media.discordapp.net/attachments/813042041739149363/1016759235444486164/Screenrecorder-2022-09-07-00-16-35-463.mp4
> 
> build https://github.com/Tommy-Geenexus/exif-eraser/releases/download/v5.2.2/app-foss-release.apk

Seems to be related to screenshots, was able to reproduce.
I will have a look as to why querying the display name does not return what's expected.

Concerning your initial suggestion, renaming will not be implemented in the near future.

**Comment by Tommy-Geenexus** [comment]
Currently no possible workaround
