### ISSUE TITLE
Feature request: Option to randomise file name

### ISSUE THREAD

**Issue by BHydden** [Tommy-Geenexus/exif-eraser#53]
ScrambledExif by default generates a random file name when it saves or shares a file. 

Some like this and some don't, so I was wondering if maybe there could be a checkbox option or something at time of save or share asking if user wants to use current default or generate a random new name.

**Comment by BHydden** [comment]
Sorry, I just found your comment in https://github.com/Tommy-Geenexus/exif-eraser/issues/52#issuecomment-1238527802

> Regarding your initial suggestion, renaming will not be implemented in the near future.

Guess based on that I'll close this request.

**Comment by Tommy-Geenexus** [comment]
This seems to be a popular demand, so will reopen this issue.
Thus far feature development has become stale due to lack of time, i'll add this to the milestone tracking the next release.
