### ISSUE TITLE
Selecting image through the app renames it, while sharing an image with the app preserves the original filename

### ISSUE THREAD

**Issue by matchboxbananasynergy** [Tommy-Geenexus/exif-eraser#54]
My understanding is that you're not interested in implementing filename randomization, as mentioned here: https://github.com/Tommy-Geenexus/exif-eraser/issues/52#issuecomment-1238291901

Therefore, this feels like a bug / unintended, especially seeing as it doesn't happen when you share the photo with the app.

**Comment by BHydden** [comment]
Bug, or hidden feature? 😅 #53

**Comment by Tommy-Geenexus** [comment]
This is pretty much covered by #52.
It's neither a bug nor feature, simply a byproduct of Android's file sharing via URI.
The method used for retrieving the image display name is the exact same for every use case, it's just that images shared via file provider have obfuscated URIs and the display name can't be retrieved (to my knowledge, without overhead).
