### ISSUE TITLE
The Date & Time doesn't clear

### ISSUE THREAD

**Issue by Soloper** [Tommy-Geenexus/exif-eraser#62]
Date & time is still the same as the original after clearing metadata.

**Comment by Tommy-Geenexus** [comment]
The file modification/access datetime is set via fs, unrelated to EXIF. It cannot be stripped.

**Comment by Tommy-Geenexus** [comment]
If you are not referring to the above, and discovered an implementation bug (which is unlikely), feel free to open an issue with detailed steps to reproduce.
