### ISSUE TITLE
"0 of 1 images modified" error when removing EXIF from .png file

### ISSUE THREAD

**Issue by notahomosapien** [Tommy-Geenexus/exif-eraser#69]
Hello
Whenever I try to remove EXIF data from a .png file, ExifEraser always gives the "0 of 1 images error". It works fine with jpg files.

**Comment by notahomosapien** [comment]
The .png file I was talking about is actually an screenshot. After some reading, It seems that screenshots captured on Android don't contain much metadata (I'm still not sure)

**Comment by Tommy-Geenexus** [comment]
Android PNG screenshots don't contain metadata.
You can verify whether this is actually the case with an external utility, such as https://exiftool.org/.

**Comment by notahomosapien** [comment]
> Android PNG screenshots don't contain metadata.

As per my device's default Gallery app, this is not the case.
![CFxMSYnWPn](https://github.com/Tommy-Geenexus/exif-eraser/assets/139213261/82db9acf-5f96-4bf0-9f49-95f3ed490d9d)

**Comment by Tommy-Geenexus** [comment]
The image dimensions are not part of the exif metadata and are being preserved for compatibility reasons.

**Comment by notahomosapien** [comment]
> The image dimensions are not part of the exif metadata and are being preserved for compatibility reasons.

But time is still EXIF metdata?
