### ISSUE TITLE
Bug to clean hundreds of images

### ISSUE THREAD

**Issue by Erz3** [Tommy-Geenexus/exif-eraser#72]
Hi,

First of all say thanks for this amazing app, I was looking something like this for a lot of time a go.

I am running 6.1.0 version and I have seen that happen some rare bug when I try cleaning a directory with hundreds of images. Exif-erase clean between one hundred and two hundred images, finish the job (delete processed image correctly) and I start again the job with the remaining images. However, at this point, those images can never be cleaned because I will always get an error, even if I change their location.

Images that can't be cleaned have got the same format like the others, and It have the same amount of KB so I think something go wrong with Exif-erase.

Happy new year!

**Comment by Tommy-Geenexus** [comment]
Hi,

can you verify whether said images actually contain metadata, for example with https://exiftool.org/ or a similar tool and report your findings? Thanks.

**Comment by Erz3** [comment]
Alright!

I have been looking metadata from cleaned images without errors and images cleaned with errors. I have not seen metadata on images cleaned with errors, however their names have not been ofuscate.

**Comment by Tommy-Geenexus** [comment]
>I have not seen metadata on both cases

Good, so the app is working as intended.

>however names of images with errors have not been ofuscate

That's because the image has not been modified, only if the image contains metadata there will be a new image saved (related issue #63).

**Comment by Erz3** [comment]
But usually in file names a lot of metadatas are preserved. App is not doing well all the process because If "randomice names" is enable, Exif-erase should process every kind of images (with or without any other metadata).

**Comment by Tommy-Geenexus** [comment]
> But usually in images names a lot of metadatas are preserved. App is not doing well all the process because If "randomice names" is enable, Exif-erase should process every kind of images (with or without any other metadata).

I agree, what you are suggesting is a different issue which has already been created [here](https://github.com/Tommy-Geenexus/exif-eraser/issues/63).
