### ISSUE TITLE
GIF Support

### ISSUE THREAD

**Issue by Coehill** [Tommy-Geenexus/exif-eraser#76]
Currently, if you share a GIF to Exif Eraser, it returns "0 of 1 images modified". Erasing metadata from gifs would be a handy feature since they are so prevalent online.

Thank you for your work on this tool and for making it available as FOSS!

**Comment by Tommy-Geenexus** [comment]
Thanks, GIF support is not planned for now, see [here](https://github.com/Tommy-Geenexus/exif-interface-extended/issues/3) as to why.
