### ISSUE TITLE
Translations via OneSky not working due to change of free plan

### ISSUE THREAD

**Issue by Tommy-Geenexus** [Tommy-Geenexus/exif-eraser#80]
Currently, translations won't work due to the free plan limiting collaborators, which means a paid plan is required to maintain public translations. 

- Figure out a where to host translations with minimal overall costs

**Comment by Aseel67** [comment]
Host the translation on Crowdin and all will be well

**Comment by Tommy-Geenexus** [comment]
Crowdin is an option, free for one project + unlim. collaborators, will have a look at it
