### ISSUE TITLE
Let me just share and skip choosing a save path

### ISSUE THREAD

**Issue by squeak9** [Tommy-Geenexus/exif-eraser#88]
Could you please add a setting that allows the app to bypass the save path prompt? I’d like it to directly change the image and share it without needing to save first. It's important that this feature also works for multiple images.

Thanks for the useful app.

**Comment by Tommy-Geenexus** [comment]
You can bypass the save path sheet by setting a default save path and enable the save path selection skip option in the settings. Is that sufficient for your use case?

**Comment by squeak9** [comment]
Oh, thanks. Yeah, that basically does it.
It's not ideal since it will leave lots duplicate images on my phone but still it's helpful. It would be perfect if it didn't save the image at all though.
But this does the job for now, a `skip saving` setting would be perfect still.

I also will mainly feed the app images through the share menu and then just re-share it if that wasn't clear.

**Comment by Tommy-Geenexus** [comment]
>It would be perfect if it didn't save the image at all though. But this does the job for now, a `skip saving` setting would be perfect still.

This currently is not possible (nor planned), so i will close this as not planned. Image deletion unfortunatly doesnt work with shared images.
